// Generated by Wrangler on Mon Oct 14 2024 11:27:08 GMT+0900 (Japan Standard Time)
// by running `wrangler types`

interface Env {
	ENVIRONMENT: "local";
	APP_URL: string;
	DATABASE_URL: string;
	SENTRY_DSN: string;
	GITHUB_CLIENT_ID: string;
	GITHUB_CLIENT_SECRET: string;
	GOOGLE_CLIENT_ID: string;
	GOOGLE_CLIENT_SECRET: string;
	TWITTER_CLIENT_ID: string;
	TWITTER_CLIENT_SECRET: string;
	SESSION_SECRET: string;
}
